extends SceneTree
func _initialize(): call_deferred("run")
func run() -> void:
	var g = load("res://scenes/main.tscn").instantiate()
	g.set_script(load("res://tests/hotdog_challenge_fixture.gd"))
	root.add_child(g);current_scene=g;g.playing=true
	var replica=load("res://tests/hotdog_replica_fixture.gd").new()
	g.add_child(replica);replica.setup(g);g._hotdog_challenge=replica;replica.set_process(false)
	var orders=replica.make_recipes(42)
	replica.sync_state("ready",0,0,orders,"idle_sway",0,1,1)
	assert(replica.customer.order==orders[0]);assert(g.tickets.has(replica.customer))
	replica.receive_sound("breakout")
	assert(replica.voice.stream.resource_path.ends_with("bossahhhhhentrance.wav") and replica.concrete.playing)
	replica.receive_sound("smash2")
	assert(replica.effects.playing and replica.effects.stream.resource_path.ends_with("smash2.wav"))
	replica.receive_sound("eat")
	assert(replica.voice.stream.resource_path.ends_with("eatboss.wav"))
	replica.receive_sound("laugh")
	assert(replica.voice.stream.resource_path.ends_with("laughboss.wav"))
	var boss_id=replica.customer.get_instance_id()
	g._mp_cull_stale_tickets({})
	assert(is_instance_valid(replica.customer) and g.tickets.has(replica.customer))
	replica.sync_state("slump",10,2,orders,"slump",.5,2,1)
	assert(not replica.can_serve() and replica.clip=="slump")
	replica.sync_state("ready",10,2,orders,"idle_wave",0,2,1,4.25,Vector3(0,0,7),1.2)
	assert(replica.order_left == 4.25 and replica.customer.position.z == 7)
	assert(replica.customer.scale.is_equal_approx(Vector3.ONE*1.2))
	assert(replica.customer.order==orders[12]);assert(replica.customer.get_instance_id()==boss_id)
	replica.sync_state("",25,2,orders,"",0,2,1)
	assert(not replica.active() and g.customers.is_empty())
	# Late join during victory must not index the finale deck out of bounds.
	replica.sync_state("victory",25,0,orders,"slump",1,4,2)
	assert(replica.phase=="victory" and is_instance_valid(replica.customer))
	assert(replica.victory_played and not replica.music.playing)
	replica.sync_state("sinking",25,0,orders,"slump",.8,4,2)
	assert(replica.customer.position.y < replica.boss_position.y - 2)
	replica.sync_state("results",25,0,orders,"slump",0,4,2)
	assert(is_instance_valid(replica.result_screen) and not replica.customer.visible)
	replica.sync_state("",25,0,orders,"",0,4,2)
	assert(replica.result_screen == null and not replica.active())
	replica.cancel();g.queue_free();await process_frame
	print("HOTDOG_REPLICA_OK: shared progress, milestone animation, late join, stale-ticket protection, cleanup")
	quit()
