extends SceneTree
func _initialize(): call_deferred("run")
func run() -> void:
	var g = load("res://scenes/main.tscn").instantiate()
	g.set_script(load("res://tests/hotdog_challenge_fixture.gd"))
	root.add_child(g);current_scene=g;g.playing=true
	var replica=load("res://tests/hotdog_replica_fixture.gd").new()
	g.add_child(replica);replica.setup(g);g._hotdog_challenge=replica;replica.set_process(false)
	var orders=replica.make_recipes(42)
	replica.sync_state("ready",0,0,orders,"idle_sway",0,1,1)
	assert(replica.customer.order==orders[0]);assert(g.tickets.has(replica.customer))
	assert(replica.next_order_preview.order == orders[1] and g.tickets.has(replica.next_order_preview))
	replica.receive_sound("breakout")
	assert(replica.voice.stream.resource_path.ends_with("bossahhhhhentrance.wav") and replica.concrete.playing)
	replica.receive_sound("smash2")
	assert(replica.effects.playing and replica.effects.stream.resource_path.ends_with("smash2.wav"))
	replica.receive_sound("eat")
	assert(replica.voice.stream.resource_path.ends_with("eatboss.wav"))
	replica.receive_sound("laugh")
	assert(replica.voice.stream.resource_path.ends_with("laughboss.wav"))
	var boss_id=replica.customer.get_instance_id()
	g._mp_cull_stale_tickets({})
	assert(is_instance_valid(replica.customer) and g.tickets.has(replica.customer))
	assert(is_instance_valid(replica.next_order_preview) and g.tickets.has(replica.next_order_preview))
	replica.sync_state("slump",10,2,orders,"slump",.5,2,1)
	assert(not replica.can_serve() and replica.clip=="slump")
	replica.concrete.stop()
	replica.sync_state("revive",10,2,orders,"revive",.275,2,1)
	assert(replica.customer.player.speed_scale > 1.0)
	assert(is_equal_approx(replica.customer.player.current_animation_position, replica.customer.player.get_animation("revive").length - .275 * replica.customer.player.speed_scale))
	replica.receive_sound("revive_roar")
	assert(replica.voice.stream == replica.sound_streams["bossahhhhhentrance"] and not replica.concrete.playing)
	for recovery in [["revive_smash_first","hammer_left",3],["revive_smash_second","hammer_double",4]]:
		replica.sync_state(recovery[0],10,2,orders,recovery[1],.4,recovery[2],1)
		assert(not replica.can_serve() and replica.clip == recovery[1])
		assert(replica.customer.player.speed_scale == 1.0 and g.slot_camera_shake_t > 0)
	var patty=load("res://scripts/patty.gd").new();g.add_child(patty);patty.heating=false;patty.cook_time=4.0;g.grill.append(patty)
	replica.receive_ground_slam(100)
	var hop=patty._done_jump_tw
	assert(is_instance_valid(hop))
	replica.receive_ground_slam(100)
	assert(patty._done_jump_tw==hop,"Reliable impact and snapshot cannot double-trigger a hop")
	hop.pause();hop.custom_step(.13)
	assert(patty._done_jump_y>.01 and patty.cook_time==4.0 and not patty.flipped_once)
	replica.sync_state("ready",10,2,orders,"idle_wave",0,2,1,4.25,Vector3(0,0,7),1.2)
	assert(replica.order_left == 4.25 and replica.customer.position.z == 7)
	assert(replica.customer.scale.is_equal_approx(Vector3.ONE*1.2))
	assert(replica.customer.order==replica.recipe_at(10));assert(replica.customer.get_instance_id()==boss_id)
	assert(replica.next_order_preview.order == replica.recipe_at(11))
	replica.sync_state("",25,2,orders,"",0,2,1)
	assert(not replica.active() and g.customers.is_empty())
	# Late join during victory must not index the finale deck out of bounds.
	replica.sync_state("victory",25,0,orders,"slump",1,4,2)
	assert(replica.phase=="victory" and is_instance_valid(replica.customer))
	assert(replica.victory_played and not replica.music.playing)
	replica.sync_state("sinking",25,0,orders,"ground_exit",.8,4,2)
	assert(replica.customer.position == replica.boss_position and replica.clip == "ground_exit")
	replica.sync_state("results",25,0,orders,"slump",0,4,2)
	assert(is_instance_valid(replica.result_screen) and not replica.customer.visible)
	replica.sync_state("",25,0,orders,"",0,4,2)
	assert(replica.result_screen == null and not replica.active())
	replica.cancel();g.queue_free();await process_frame
	print("HOTDOG_REPLICA_OK: shared progress, milestone animation, late join, stale-ticket protection, cleanup")
	quit()
