extends SceneTree
const Customer = preload("res://scripts/customer.gd")
func _initialize(): call_deferred("run")
func run():
 var parent = Node3D.new()
 root.add_child(parent)
 var customers = []
 for i in 2:
  var c = Customer.new()
  c.setup(["bun_bottom","patty","bun_top"],Color.WHITE,9999,0,0,0,-1,{"format_version":8,"top_catalog_version":1,"top_style":1,"bottom_catalog_version":1,"bottom_style":2,"shoe_catalog_version":1,"shoe_style":1},true)
  parent.add_child(c)
  c.set_process(false)
  customers.append(c)
 await process_frame
 var first_body = customers[0].find_child("CreatedCustomer",true,false)
 var second_body = customers[1].find_child("CreatedCustomer",true,false)
 var first_skin = first_body.get("_skin_material")
 var second_skin = second_body.get("_skin_material")
 assert(first_skin != second_skin and first_skin.shader == second_skin.shader,"Customers must share shader programs but retain their own skin materials")
 second_body.skin_color = Color.BLUE
 assert(first_skin.get_shader_parameter("skin_color") != second_skin.get_shader_parameter("skin_color"),"Shared programs must not share customer colors")
 var top = customers[0].find_child("FittedTop",true,false)
 var original = top.get_surface_override_material(0)
 var original_shader = original.shader
 customers[0].complete_serve(10,false)
 assert(top.get_surface_override_material(0) == original,"Serve must retain the opaque clothing material")
 assert(customers[0]._leave_fade_materials.is_empty(),"Serve must not build fade materials")
 customers[0]._apply_leave_fade_alpha(0.4)
 var faded = top.get_surface_override_material(0)
 assert(faded != original and faded.shader != original_shader)
 assert(not original_shader.code.contains("fade_alpha"),"Shared source shader must stay untouched")
 customers[1]._apply_leave_fade_alpha(0.8)
 var second = customers[1].find_child("FittedTop",true,false).get_surface_override_material(0)
 assert(second != faded and second.shader == faded.shader,"Customers share shader programs, not color/opacity uniforms")
 assert(is_equal_approx(second.get_shader_parameter("fade_alpha"),0.8))
 assert(is_equal_approx(faded.get_shader_parameter("fade_alpha"),0.4))
 var cached_count = Customer._leave_fade_shader_cache.size()
 customers[0]._apply_leave_fade_alpha(0.2)
 assert(top.get_surface_override_material(0) == faded,"Fade frames must retain material identity")
 assert(Customer._leave_fade_shader_cache.size() == cached_count)
 var cutout = ShaderMaterial.new()
 cutout.shader = Shader.new()
 cutout.shader.code = "shader_type spatial;\nvoid fragment() { ALPHA = 0.5; ALBEDO = vec3(1.0); }"
 var mesh = MeshInstance3D.new()
 mesh.mesh = BoxMesh.new()
 mesh.material_override = cutout
 var c = Customer.new()
 parent.add_child(c)
 c.set_process(false)
 c.add_child(mesh)
 c._apply_leave_fade_alpha(0.5)
 assert(mesh.material_override is ShaderMaterial)
 assert(mesh.material_override.shader.code.contains("ALPHA *= fade_alpha"),"Fade must preserve existing transparency masks")
 assert(is_equal_approx(mesh.material_override.get_shader_parameter("fade_alpha"),0.5))
 var game = load("res://scripts/game.gd").new()
 var feed = VBoxContainer.new()
 root.add_child(feed)
 game.phone_feed_box = feed
 game.social_reviews = [{"id":1,"who":"First","text":"Good burger","stars":4.0}]
 game._refresh_phone_feed()
 var picture = ImageTexture.create_from_image(Image.create(112,112,false,Image.FORMAT_RGBA8))
 game.social_reviews[0]["pic"] = picture
 game.social_reviews[0]["pic_png"] = PackedByteArray([1,2,3])
 game._refresh_phone_feed()
 var card = feed.get_child(0)
 game._refresh_phone_feed()
 assert(feed.get_child(0) == card,"Unchanged reviews must reuse their UI")
 game.social_reviews[0]["pic_png"] = PackedByteArray([9,8,7])
 game._refresh_phone_feed()
 assert(feed.get_child(0) == card,"Network image encoding must not invalidate the UI")
 feed.hide()
 game.social_reviews.push_front({"id":2,"who":"Second","text":"Great burger","stars":5.0})
 game._refresh_phone_feed()
 assert(feed.get_child(0) == card,"Hidden feed must not rebuild")
 feed.show()
 game._refresh_phone_feed()
 assert(feed.get_child_count() == 2,"Showing the feed must display new reviews")
 card = feed.get_child(0)
 game._refresh_phone_feed()
 assert(feed.get_child(0) == card)
 game._phone_reply_open_id = 2
 game._refresh_phone_feed()
 assert(not is_instance_valid(card),"Reply menu changes must refresh the displayed card")
 game.free()
 feed.queue_free()
 parent.queue_free()
 await process_frame
 print("SERVE_COMPLETION_CACHE_OK")
 quit()
